version: "3.5"

services:
  api01:
    build:
      context: ./src/RinhaBackend2024
      dockerfile: Dockerfile
    image: fvck_ms1
    hostname: api01
    environment:
      - APIPORT=80
      - DB_HOSTNAME=Dev
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"

  api02:
    <<: *api 
    hostname: fvck_ms2
    environment:
      - APIPORT=80
      - DB_HOSTNAME=D
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999" 
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "10MB"

  db:
    image: mcr.microsoft.com/mssql/server:latest
    hostname: db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Express
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.13"
          memory: "140MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
